# Dockerfile.nginx
FROM nginx:alpine

# Copier le fichier de configuration Nginx dans le conteneur
COPY default.conf /etc/nginx/conf.d/default.conf

# Copier le contenu de l'application dans le répertoire /app
COPY . /app
