version: '3.8'

services:
  http:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Redirige le port 80 du conteneur vers le port 8080 de l'hôte
    volumes:
      - ./wordpress:/var/www/html            # Dossier WordPress
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Monté vers le fichier de configuration Nginx
    depends_on:
      - php
    networks:
      - wordpress-network

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./wordpress:/var/www/html            # Dossier WordPress
    networks:
      - wordpress-network

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql                # Volume pour les données de MySQL
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data:  # Volume pour persister les données de la base de données
